services:
  postgres:
    image: postgres:16
    container_name: postgres
    environment:
      POSTGRES_DB: shop
      POSTGRES_USER: shopuser
      POSTGRES_PASSWORD: shoppass
    ports:
      - "5432:5432"

  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"

  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    ports:
      - "5672:5672"  # RabbitMQ default port
      - "15672:15672" # RabbitMQ management plugin (web UI)
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

#  product-service:
#    build:
#      context: .
#      dockerfile: product-service/Dockerfile
#    container_name: product-service
#    ports:
#      - "8082:8082"
#    depends_on:
#      - postgres
#    environment:
#      SPRING_PROFILES_ACTIVE: docker

  cart-service:
    build:
      context: .
      dockerfile: cart-service/Dockerfile
    container_name: cart-service
    ports:
      - "8081:8081"
    depends_on:
      - postgres
      - redis
      - rabbitmq
#      - product-service
    environment:
      SPRING_PROFILES_ACTIVE: docker

#  order-service:
#    build:
#      context: .
#      dockerfile: order-service/Dockerfile
#    container_name: order-service
#    ports:
#      - "8083:8083"
#    depends_on:
#      - rabbitmq
#    environment:
#      SPRING_PROFILES_ACTIVE: docker

# Volumes do MongoDB - wolumeny zapobiegają usunieciu danych gdy kontener usuwany/zatrzymywany
volumes:
  postgres-data:

