server:
  port: 8080
  address: 0.0.0.0

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      default-filters:
        - AddResponseHeader=X-Gateway, ShopGateway
      httpclient:
        connect-timeout: 5000
        response-timeout: 10s
