server:
  port: 8082

messaging:
  exchange:
    cart-events: cart.events.exchange
    order-events: order.events.exchange

spring:
  cache:
    type: REDIS
  application:
    name: product-service
  datasource:
    url: jdbc:postgresql://postgres:5432/shop
    username: shopuser
    password: shoppass
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
  rabbitmq:
    host: rabbitmq
    port: 5672
  data:
    redis:
      port: 6379
      host: redis
external:
  cart-service:
    base-url: http://cart-service:8081