server:
  port: 8082

messaging:
  exchange:
    cart-events: cart.events.exchange
    order-events: order.events.exchange

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/shop
    username: shopuser
    password: shoppass
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  rabbitmq:
    host: localhost
    port: 5672
  application:
    name: product-service
  data:
    redis:
      host: localhost
      port: 6379