server:
  port: 8082

messaging:
  exchange:
    cart-events: cart.events.exchange
    order-events: order.events.exchange

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/shop
    username: shopuser
    password: shoppass
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  redis:
    host: localhost
    port: 6379
  rabbitmq:
    host: localhost
    port: 5672
  application:
    name: cart-service

external:
  product-service:
    base-url: http://localhost:8081